### ISSUE TITLE
进度条卡 79.92%是什么鬼？

### ISSUE THREAD

**Issue by DrRoyLiu** [Shaman05/electron-launch-page#1]
除了demo里面的main.html之外，打开本地文件、http网页都卡79.92%

**Comment by Shaman05** [comment]
实际使用中业务页面（demo里的mian.html）在调用 Elp.render.ready(); 后，主进程才能收到页面加载完毕的消息，进度条才会继续走下去的。

**Comment by DrRoyLiu** [comment]
假设index.html调用了render，然后从index.html跳往book.html，再从book.htmlt跳往index.html时会有error弹窗。加上try catch消除这一弹窗
